### ISSUE TITLE
Simulink Model on dSpace

### ISSUE THREAD

**Issue by renegadephysicist** [olmerg/vilma_ma#3] opened 2019-06-11 10:59 UTC
Hi,

First of all thanks for this excellent contribution.

I was wondering if you have provided access to the Simulink model that the ROS node communicates with. I'm interested in how the checksum and UDP protocol is implemented on the dSpace in Simulink.

My initial understanding was that you compile an S-function using [maudp.h](https://gitlab.com/vilma_unicamp/vilma_ma_ros/blob/master/include/maudp.h) and [protocoloc.h](https://gitlab.com/vilma_unicamp/vilma_ma_ros/blob/master/include/protocoloc.h) on dSpace.

However maudp.hpp doesn't look like it could be compiled in matlab (maybe the unused matlabdata() funciton is used for this?)

**Comment by olmerg** [comment] 2019-06-12 02:30
Hi,

Please read the thread (Procedure to run the project)[https://github.com/olmerg/vilma_ma/issues/2] to understand better the architecture.
The idea was that I only use the (protocoloc.h)[(https://gitlab.com/vilma_unicamp/vilma_ma_ros/blob/master/include/protocoloc.h)] in an s-function, for udp socket I use the licensed udp blocks that provided the dspace.

**Comment by olmerg** [comment] 2019-06-12 02:32
please comment in the other issue
Duplicate of #2

**Closed as completed by olmerg** 2019-06-12 02:32 UTC
